### ISSUE TITLE
Need ability to target specific versions of MSO

### ISSUE THREAD

**Issue by boylec** [maizzle/tailwindcss-mso#22]
Feature request/idea:

```html
<!--[!if gte mso 9]><!-->
 // This will be ignored by Outlook 2007
<![endif]-->

<!--[!if gte mso 15]><!-->
 // This will be ignored by Outlook 2013
<![endif]-->

<!--[if !mso]><!-->
 // This will be ignored by all Microsoft Outlook
<!--<![endif]-->
```

This causes Microsoft to ignore certain styles based on ranges.

Would be super useful if we could have tailwind directives like

```
class="mso-gte-9:<some utility>"
```

 for example.

**Comment by cossssmin** [comment]
Tailwind CSS only generates CSS, so you can't use it to write HTML content inside MSO comments.

If you're using Maizzle then you can already do this with the [`<outlook>` tag](https://maizzle.com/docs/tags#outlook). Also, for targeting email clients with CSS, there's [tailwindcss-email-variants](https://github.com/maizzle/tailwindcss-email-variants) (also included in Maizzle).
